default_platform(:android)

platform :android do
  desc "Deploy AAB to Play Store production"
  lane :deploy do
    upload_to_play_store(
      track: 'production',
      aab: 'app/build/outputs/bundle/release/app-release.aab',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
    )
  end
end
