package com.inspiredandroid.betabase.data

import androidx.compose.runtime.Immutable
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlin.time.Clock
import kotlin.time.Duration
import kotlin.time.Duration.Companion.days
import kotlin.time.Instant

@Immutable
data class AthleteFeedItem(
    val athlete: Athlete,
    val video: YoutubeVideo,
)

/**
 * Builds one feed of recent athlete uploads from the prebuilt combined JSON
 * served by [AthleteVideosFeedSource] (regenerated by the refresh-athlete-videos
 * GitHub Action). A single request replaces the previous fan-out of one Atom feed
 * per athlete, which YouTube rate-limited per IP. The source caches the JSON on
 * disk, so cold start can paint from disk before the network refresh lands; the
 * assembled result is then held in memory to short-circuit subsequent calls.
 */
class AthleteFeedRepository(
    private val athletesRepository: AthletesRepository,
    private val videosSource: AthleteVideosFeedSource,
    private val maxItems: Int = 25,
    private val maxAge: Duration = 90.days,
) {
    private val mutex = Mutex()
    private var cached: List<AthleteFeedItem>? = null

    fun loadRecent(): Flow<Result<List<AthleteFeedItem>>> = flow {
        mutex.withLock { cached }?.let {
            emit(Result.success(it))
            return@flow
        }

        val athletes = runCatching {
            athletesRepository.load().filter { !it.youtubeChannelId.isNullOrBlank() }
        }.getOrElse {
            emit(Result.failure(it))
            return@flow
        }
        if (athletes.isEmpty()) {
            emit(Result.success(emptyList()))
            return@flow
        }
        val cutoff = Clock.System.now() - maxAge

        videosSource.cached()?.let { byChannel ->
            val items = assemble(athletes, byChannel, cutoff)
            if (items.isNotEmpty()) emit(Result.success(items))
        }

        val fresh = runCatching { assemble(athletes, videosSource.fetch(), cutoff) }
        fresh.onSuccess { items -> mutex.withLock { cached = items } }
        emit(fresh)
    }

    private fun assemble(
        athletes: List<Athlete>,
        byChannel: Map<String, List<YoutubeVideo>>,
        cutoff: Instant,
    ): List<AthleteFeedItem> = athletes.asSequence()
        .flatMap { athlete ->
            byChannel[athlete.youtubeChannelId].orEmpty().asSequence()
                .map { AthleteFeedItem(athlete = athlete, video = it) }
        }
        .filter { it.video.publishedAt >= cutoff }
        .sortedByDescending { it.video.publishedAt }
        .take(maxItems)
        .toList()
}
